import Head from "next/head";
import Image from "next/image";
import bLogo from "../../../CustomerAssets/LOGO.png";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Lone Star Garage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}></div>

        <div className={styles.center}>/**Main display */</div>

        <div className={styles.grid}>
          <Image
            className={styles.logo}
            src={bLogo}
            alt="Logo"
            width={375}
            height={200}
            priority
          />
        </div>
      </main>
    </>
  );
}
